version: '3.6'

services:
  # Dependency services section
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
      - ./grafana-data:/var/lib/grafana
    environment:
      - GF_SERVER_HTTP_PORT=3007
    ports:
      - 3007:3007
  mongo:
    image: mongo:4.0.5
    volumes:
      - ./mongo-data:/data/db
    ports:
      - 27017:27017
  # Apps section
  order_be:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - PORT=8181
      - LOG_LEVEL=debug
      - MONGO_DSN=${MONGO_DSN_ORDERS}
    ports:
      - '8181:8181'
    links:
      - mongo
    depends_on:
      - mongo
